name: darksky_weather
description: A dart library for interfacing with the Dark Sky Weather API.
version: 1.2.2
author: 'rinukkusu <rinukkusu@auen.land>'
homepage: https://github.com/rinukkusu/darksky-weather-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  intl: ^0.15.7
  json_annotation: ^2.0.0
  http: '^0.12.0'

dev_dependencies:
  test: ^1.3.0
  json_serializable: ^2.0.0
  build_runner: ^1.1.2

